# Generated by Django 4.2 on 2025-02-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_userprofile_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
