# Generated by Django 4.2 on 2025-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='college_id',
            field=models.CharField(max_length=20),
        ),
    ]
